### PR TITLE
LICENSE change to BSD-3

### PR DESCRIPTION
**Pull request by ktran**

### CODE REVIEW

**Review by bmeurer — COMMENTED** [review]
`LICENSE` file shouldn't contain the `// ` comment markers

**Comment by ktran** [comment]
Updated!

**Review by bmeurer — APPROVED** [review]

**Review by bmeurer — COMMENTED** [review]
Please also update the license field in the `package.json` file.

**Comment by ktran** [comment]
Done!

**Review by bmeurer — APPROVED** [review]
Thanks!

**Pull request merged**
